name: .NET Core 8 MVC CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET SDK 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Restore Dependencies
      run: dotnet restore OnlineShop/OnlineShop.sln 

    - name: Build Project
      run: dotnet build OnlineShop/OnlineShop.sln --configuration Release --no-restore 

    - name: Run Tests
      run: dotnet test OnlineShop/OnlineShop.sln --configuration Release --no-build 

    - name: Publish Application
      run: dotnet publish OnlineShop/OnlineShop.Web/OnlineShop.Web.csproj --configuration Release --output ./publish_output

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mvc-app-published
        path: ./publish_output